In [1]:
import csv
import numpy as np
import py_vollib
from py_vollib.black_scholes.implied_volatility import implied_volatility as iv

In [4]:
# import data

TEST_CHART_1_FILE = "QuoteSequence/test_chart_1.csv"

def import_data(file_name : str):
    stock_prices = []
    with open(file_name, newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='|')
        for row in reader:
            if len(stock_prices) == 0:
                stock_prices.append(np.array([0, float(row[1])]))
            else:
                price = float(row[1])
                stock_prices.append(np.array([int(row[0]), price]))

    stock_prices = np.array(stock_prices)
    return stock_prices

def calculate_volatility(filename=TEST_CHART_1_FILE):
    raw_data = import_data(filename)
    trimmed_data = np.delete(raw_data, 0, 0)
    unit_profits = []
    prev_price = raw_data[0,1]
    stock_prices_array = trimmed_data[:,1]
    for price in stock_prices_array:
       unit_profit = np.log(price / prev_price)
       unit_profits.append(unit_profit)
       prev_price = price

    unit_profits = np.array(unit_profits)
    mat = np.append(trimmed_data, unit_profits.reshape((len(unit_profits), 1)), axis=1)
    print(mat)

    sigma = (np.std(unit_profits) * np.sqrt(256))
    print(sigma)
    return sigma

[[ 1.00000000e+00  5.56800000e+03  1.61768706e-03]
 [ 2.00000000e+00  5.60100000e+03  5.90923020e-03]
 [ 3.00000000e+00  5.56100000e+03 -7.16720502e-03]
 [ 4.00000000e+00  5.64800000e+03  1.55235520e-02]
 [ 5.00000000e+00  5.67100000e+03  4.06396884e-03]
 [ 6.00000000e+00  5.68700000e+03  2.81739929e-03]
 [ 7.00000000e+00  5.61300000e+03 -1.30975324e-02]
 [ 8.00000000e+00  5.65800000e+03  7.98513692e-03]
 [ 9.00000000e+00  5.75300000e+03  1.66509850e-02]
 [ 1.00000000e+01  5.73700000e+03 -2.78503226e-03]
 [ 1.10000000e+01  5.41400000e+03 -5.79482344e-02]
 [ 1.20000000e+01  5.24700000e+03 -3.13317065e-02]
 [ 1.30000000e+01  5.45400000e+03  3.86927997e-02]
 [ 1.40000000e+01  5.37300000e+03 -1.49628727e-02]
 [ 1.50000000e+01  5.37900000e+03  1.11607154e-03]
 [ 1.60000000e+01  5.33000000e+03 -9.15124511e-03]
 [ 1.70000000e+01  5.43700000e+03  1.98762000e-02]
 [ 1.80000000e+01  5.50700000e+03  1.27925721e-02]
 [ 1.90000000e+01  5.38500000e+03 -2.24026997e-02]
 [ 2.00000000e+01  5.42100000e+