In [75]:
import csv
import numpy as np
import py_vollib
from py_vollib.black_scholes.implied_volatility import implied_volatility as iv

In [76]:
# import data

def import_data(file_name : str):
    stock_prices = []
    with open(file_name, newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='|')
        for row in reader:
            if len(stock_prices) == 0:
                stock_prices.append(np.array([0, float(row[1])]))
            else:
                price = float(row[1])
                stock_prices.append(np.array([int(row[0]), price]))

    stock_prices = np.array(stock_prices)
    return stock_prices

In [77]:
raw_data = import_data("QuoteSequence/test_chart_1.csv")
print(raw_data)
trimmed_data = np.delete(raw_data, 0, 0)
unit_profits = []
prev_price = raw_data[0,1]
stock_prices_array = trimmed_data[:,1]
for price in stock_prices_array:
       unit_profit = np.log(price / prev_price)
       unit_profits.append(unit_profit)
       prev_price = price

unit_profits = np.array(unit_profits)
mat = np.append(trimmed_data, unit_profits.reshape((len(unit_profits), 1)), axis=1)
print(mat)

sigma = (np.std(unit_profits) * np.sqrt(256))
print(sigma)

[[0.000e+00 5.559e+03]
 [1.000e+00 5.568e+03]
 [2.000e+00 5.601e+03]
 [3.000e+00 5.561e+03]
 [4.000e+00 5.648e+03]
 [5.000e+00 5.671e+03]
 [6.000e+00 5.687e+03]
 [7.000e+00 5.613e+03]
 [8.000e+00 5.658e+03]
 [9.000e+00 5.753e+03]
 [1.000e+01 5.737e+03]
 [1.100e+01 5.414e+03]
 [1.200e+01 5.247e+03]
 [1.300e+01 5.454e+03]
 [1.400e+01 5.373e+03]
 [1.500e+01 5.379e+03]
 [1.600e+01 5.330e+03]
 [1.700e+01 5.437e+03]
 [1.800e+01 5.507e+03]
 [1.900e+01 5.385e+03]
 [2.000e+01 5.421e+03]]
[[ 1.00000000e+00  5.56800000e+03  1.61768706e-03]
 [ 2.00000000e+00  5.60100000e+03  5.90923020e-03]
 [ 3.00000000e+00  5.56100000e+03 -7.16720502e-03]
 [ 4.00000000e+00  5.64800000e+03  1.55235520e-02]
 [ 5.00000000e+00  5.67100000e+03  4.06396884e-03]
 [ 6.00000000e+00  5.68700000e+03  2.81739929e-03]
 [ 7.00000000e+00  5.61300000e+03 -1.30975324e-02]
 [ 8.00000000e+00  5.65800000e+03  7.98513692e-03]
 [ 9.00000000e+00  5.75300000e+03  1.66509850e-02]
 [ 1.00000000e+01  5.73700000e+03 -2.78503226e-03]
 [ 1.1